apiVersion: v1
kind: Secret
metadata:
  name: secret-sql-auth
  namespace: api
type: Opaque
stringData:
  # You can include additional key value pairs as you do with Opaque Secrets
  SQL_USER: REDACTED
  SQL_PASSWORD: REDACTED
  SQL_SERVER: "REDACTED.database.windows.net"
  #SQL_DBNAME: "REDACTED"